### ISSUE TITLE
Fix: Save `metadata` fields in database

### ISSUE THREAD

**Issue by ericdrosas87** [lsst-epo/canto-dam-assets#17]
Currently the `metadata` nested fields are listed as available for querying in the graphQL interface, but are not saved to the database and thus are not queryable. This fix addresses that issue by saving the `metadata` fields to the database.

**Comment by ericdrosas87** [comment]
Upon reviewing the Canto API and reviewing some of the responses in POSTMan it seems that the album endpoint _doesn't_ actually return the `metadata` field for some reason. I'm going to reach out to Canto support to get clarification and if this is the case then I will close out this ticket as `not planned`.

**Comment by khalwat** [comment]
From memory, the plugin saves the entire response from Canto. So if it's not in the database, it didn't come back from Canto.

It's possible there's a separate API endpoint that you can ping to return the metadata, and then stitch it together, but I don't know for sure.

**Comment by ericdrosas87** [comment]
@khalwat All good Andrew, I just requested a feature for Canto to provide field parity between the individual image details response and the album details response. Truthfully there's not much in the `metadata` object that could be of use - I just wanted to make sure the plugin wasn't missing it in the save action.

**Comment by ericdrosas87** [comment]
From Canto support:

```
Thank you for reaching out. This isn't a bug. The metadata is currently not available via the "List content of a specific album" endpoint. I am happy to open a feature request for this is you'd like.
```

I have requested said feature - I'm closing this out as not planned.

**Comment by khalwat** [comment]
From memory, there was somewhere that I did two separate requests to stitch together the desired information from separate endpoints.

But I think that was taken out for some reason at some point, as I can't see it in the code after a quick look. Maybe it'll be in the Git history tho.
